# Metrics Pipeline — End-to-End Test

Three scenarios tested in order:

| Scenario | Users | Wallets per user |
|----------|-------|------------------|
| **1** | 1 | 1 |
| **2** | 1 | all (3) |
| **3** | both (2) | all |

Each scenario:
1. Cleans up any prior state (MongoDB + staging dir)
2. Stages **Batch A** (`combined_tx_batch_1,2,3`) → runs `first_time_flow` per wallet
3. Stages **Batch B** (`combined_tx_batch_4,5`) → runs `daily_flow` per wallet
4. Shows the logger output inline (PREVIOUS RUN → DELTA BATCH → FINAL RESULT)

> **Run all cells top-to-bottom.** Each scenario has a cleanup cell at the top — re-running a scenario individually is safe.

## 0 · Discover available data

In [1]:
from pathlib import Path

for user_dir in sorted(Path("tmp/user").iterdir()):
    if not user_dir.is_dir():
        continue
    wallets = sorted(d.name for d in user_dir.iterdir() if d.is_dir() and (d / "normal").exists())
    print(f"user_id : {user_dir.name}")
    for w in wallets:
        print(f"  wallet: {w}")

user_id : 69d693b1ba9f20d582dae331
  wallet: 0x02d650eea6458794b57492aca061fdbd26d97767
  wallet: 0x353479020cd3d3327af1589ad73d067c75f2dece
  wallet: 0x9f56506dea67eb73f1f2887fbcceca223ee71a42
user_id : 69e29d7ebb75c92bdac43fe1
  wallet: 0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9
  wallet: 0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691

## 1 · Setup

In [2]:
import os
from dotenv import load_dotenv
load_dotenv()
print("MONGODB_URI :", os.environ.get("MONGODB_URI", "NOT SET"))
print("MONGODB_DB  :", os.environ.get("MONGODB_DB",  "NOT SET (defaults to 'nucleus')"))

MONGODB_URI : mongodb://root:nucleus_secret_pass@187.77.5.157:27018/nucleus?authSource=admin
MONGODB_DB  : db_name

In [3]:
# Auto-reload any metrics_pipeline module the moment its .py file changes on disk.
# This means changes to pipeline.py, calculator.py, etc. take effect immediately
# in the running kernel — no restart needed.
%load_ext autoreload
%autoreload 2

In [4]:
import shutil, json, logging
from pathlib import Path
from datetime import datetime, timezone
import polars as pl

pl.Config.set_fmt_str_lengths(100)

SRC_ROOT  = Path("tmp/user")
TEST_ROOT = Path("tmp_test")
BATCH_A   = [1, 2, 3]
BATCH_B   = [4, 5]

# All users and wallets present in the test dataset
USERS = {
    "69d693b1ba9f20d582dae331": [
        "0x02d650eea6458794b57492aca061fdbd26d97767",
        "0x353479020cd3d3327af1589ad73d067c75f2dece",
        "0x9f56506dea67eb73f1f2887fbcceca223ee71a42",
    ],
    "69e29d7ebb75c92bdac43fe1": [
        "0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9",
        "0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691",
    ],
}

# ── helpers ───────────────────────────────────────────────────────────────────

def stage(user_id, wallet_address, batches):
    """Copy the selected batch files into the staging directory."""
    dest = TEST_ROOT / user_id / wallet_address / "normal"
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    for i in batches:
        src = SRC_ROOT / user_id / wallet_address / "normal" / f"combined_tx_batch_{i}.parquet"
        shutil.copy2(src, dest / src.name)
    print(f"  staged  wallet={wallet_address[:14]}…  batches={batches}")

def cleanup(user_id):
    """Delete MongoDB document and staging files for a user."""
    from metrics_pipeline.mongo import get_collection
    r = get_collection().delete_one({"user_id": user_id})
    print(f"  MongoDB : removed {r.deleted_count} doc  user={user_id}")
    d = TEST_ROOT / user_id
    if d.exists():
        shutil.rmtree(d)
        print(f"  Staging : removed {d}")

def show_doc(doc, title=None):
    """Pretty-print a user_wise_metrics document."""
    if title:
        print(f"\n{'─'*60}")
        print(f"  {title}")
        print(f"{'─'*60}")
    top = {k: v for k, v in doc.items() if k not in ("wallets",)}
    print(json.dumps(top, indent=2, default=str))
    for w in doc.get("wallets", []):
        print(f"\n  wallet : {w['wallet_address']}")
        print(f"           wallet_age={w['wallet_age_days']}d  active_days={w['active_days']}  "
              f"tx_count={w['total_transactions_count']}  first_tx={w['_first_tx_date']}")
        for c in w.get("chains", []):
            print(f"    chain={c['chain']:<12} wallet_age={c['wallet_age_days']}d  "
                  f"active_days={c['active_days']:<4} tx_count={c['total_transactions_count']:<5} "
                  f"gas={c['total_gas_burned']:.6f}  first_tx={c['_first_tx_date']}")

print("Setup OK")

Setup OK

In [5]:
from metrics_pipeline.logger import logger

logger.handlers.clear()
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s  %(levelname)-8s  %(message)s", datefmt="%H:%M:%S"))
logger.addHandler(handler)
logger.setLevel(logging.INFO)
print("Logger ready")

Logger ready

---
## Scenario 1 · Single user, single wallet

- **User** : `69d693b1ba9f20d582dae331`
- **Wallet**: `0x02d650eea6458794b57492aca061fdbd26d97767`
- **Batch A** (batches 1-3) → `first_time_flow`
- **Batch B** (batches 4-5) → `daily_flow`

In [6]:
S1_USER   = "69d693b1ba9f20d582dae331"
S1_WALLET = "0x02d650eea6458794b57492aca061fdbd26d97767"

print("── Cleanup ──")
cleanup(S1_USER)

── Cleanup ──
  MongoDB : removed 1 doc  user=69d693b1ba9f20d582dae331
  Staging : removed tmp_test/69d693b1ba9f20d582dae331

### Batch A → first_time_flow

In [7]:
from metrics_pipeline.pipeline import first_time_flow

stage(S1_USER, S1_WALLET, BATCH_A)
print()
first_time_flow(S1_USER, S1_WALLET, TEST_ROOT)

  staged  wallet=0x02d650eea645…  batches=[1, 2, 3]

04:34:33  INFO      PREVIOUS RUN  no existing document found — this is a first-time run
04:34:33  INFO      FIRST-TIME BATCH  wallet=0x02d650eea6458794b57492aca061fdbd26d97767  ──────────────────────────────────────
04:34:33  INFO          wallet-level active_days in this batch: 67
04:34:33  INFO            chain=ethereum     first_tx=2024-02-22  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:34:33  INFO            chain=polygon      first_tx=2021-06-07  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:34:33  INFO      ────────────────────────────────────────────────────────────────────────
04:34:33  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:34:33  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:34:33  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:34:33  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:34:33  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:34:33  INFO      ────────────────────────────────────────────────────────────────────────

In [8]:
from metrics_pipeline.mongo import fetch_user_doc

doc_s1_a = fetch_user_doc(S1_USER)
assert doc_s1_a, "Document not found!"
show_doc(doc_s1_a, "After Batch A")

────────────────────────────────────────────────────────────
  After Batch A
────────────────────────────────────────────────────────────
{
  "user_id": "69d693b1ba9f20d582dae331",
  "wallet_age_days": 1809,
  "active_days": 67,
  "total_transactions_count": 1105,
  "_first_tx_date": "2021-06-07",
  "last_updated_date": "2026-05-21T04:34:33.281484+00:00"
}

  wallet : 0x02d650eea6458794b57492aca061fdbd26d97767
           wallet_age=1809d  active_days=67  tx_count=1105  first_tx=2021-06-07
    chain=ethereum     wallet_age=819d  active_days=3    tx_count=5     gas=0.081355  first_tx=2024-02-22
    chain=polygon      wallet_age=1809d  active_days=64   tx_count=1100  gas=2.328805  first_tx=2021-06-07

### Batch B → daily_flow

In [9]:
from metrics_pipeline.pipeline import daily_flow

stage(S1_USER, S1_WALLET, BATCH_B)
print()
daily_flow(S1_USER, S1_WALLET, TEST_ROOT)

  staged  wallet=0x02d650eea645…  batches=[4, 5]

04:34:35  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:34:35  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:34:35  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:34:35  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:34:35  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:34:35  INFO      ────────────────────────────────────────────────────────────────────────
04:34:35  INFO      DELTA BATCH  wallet=0x02d650eea6458794b57492aca061fdbd26d97767  ──────────────────────────────────────
04:34:35  INFO          wallet-level active_days in this batch: 59
04:34:35  INFO            chain=ethereum     first_tx=2024-02-23  active_days=2     tx_count=2      gas_burned=0.002559 ETH
04:34:35  INFO            chain=polygon      first_tx=2021-06-07  active_days=57    tx_count=732    gas_burned=1.314328 ETH
04:34:35  INFO      ────────────────────────────────────────────────────────────────────────
04:34:36  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:34:36  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:34:36  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:34:36  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:34:36  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:34:36  INFO      ────────────────────────────────────────────────────────────────────────

In [10]:
doc_s1_b = fetch_user_doc(S1_USER)
show_doc(doc_s1_b, "After Batch B")

────────────────────────────────────────────────────────────
  After Batch B
────────────────────────────────────────────────────────────
{
  "user_id": "69d693b1ba9f20d582dae331",
  "wallet_age_days": 1809,
  "active_days": 126,
  "total_transactions_count": 1839,
  "_first_tx_date": "2021-06-07",
  "last_updated_date": "2026-05-21T04:34:35.399219+00:00"
}

  wallet : 0x02d650eea6458794b57492aca061fdbd26d97767
           wallet_age=1809d  active_days=126  tx_count=1839  first_tx=2021-06-07
    chain=ethereum     wallet_age=819d  active_days=5    tx_count=7     gas=0.083914  first_tx=2024-02-22
    chain=polygon      wallet_age=1809d  active_days=121  tx_count=1832  gas=3.643133  first_tx=2021-06-07

### Batch A vs Final diff

In [11]:
chains_a = {c["chain"]: c for w in doc_s1_a["wallets"] for c in w["chains"]}
chains_b = {c["chain"]: c for w in doc_s1_b["wallets"] for c in w["chains"]}

rows = []
for chain in sorted(set(chains_a) | set(chains_b)):
    ca, cb = chains_a.get(chain, {}), chains_b.get(chain, {})
    rows.append({
        "chain":              chain,
        "active_days_A":      ca.get("active_days"),
        "active_days_final":  cb.get("active_days"),
        "tx_count_A":         ca.get("total_transactions_count"),
        "tx_count_final":     cb.get("total_transactions_count"),
        "gas_A":              ca.get("total_gas_burned"),
        "gas_final":          cb.get("total_gas_burned"),
    })
pl.DataFrame(rows)

shape: (2, 7)
┌──────────┬───────────────┬──────────────────┬────────────┬────────────────┬──────────┬───────────┐
│ chain    ┆ active_days_A ┆ active_days_fina ┆ tx_count_A ┆ tx_count_final ┆ gas_A    ┆ gas_final │
│ ---      ┆ ---           ┆ l                ┆ ---        ┆ ---            ┆ ---      ┆ ---       │
│ str      ┆ i64           ┆ ---              ┆ i64        ┆ i64            ┆ f64      ┆ f64       │
│          ┆               ┆ i64              ┆            ┆                ┆          ┆           │
╞══════════╪═══════════════╪══════════════════╪════════════╪════════════════╪══════════╪═══════════╡
│ ethereum ┆ 3             ┆ 5                ┆ 5          ┆ 7              ┆ 0.081355 ┆ 0.083914  │
│ polygon  ┆ 64            ┆ 121              ┆ 1100       ┆ 1832           ┆ 2.328805 ┆ 3.643133  │
└──────────┴───────────────┴──────────────────┴────────────┴────────────────┴──────────┴───────────┘

### Sanity check — A+B vs all-5-batches ground truth

In [12]:
src_all = SRC_ROOT / S1_USER / S1_WALLET / "normal"
df_all = pl.read_parquet(str(src_all / "*.parquet")).with_columns(
    pl.from_epoch(pl.col("timeStamp").cast(pl.Int64), time_unit="s").dt.date().alias("tx_date"),
    pl.col("gasUsed").cast(pl.Int64),
    pl.col("gasPrice").cast(pl.Int64),
)

exp_tx    = df_all["hash"].n_unique()
exp_days  = df_all["tx_date"].n_unique()
exp_first = str(df_all["tx_date"].min())
exp_gas_by_chain = (
    df_all.filter(pl.col("from") == S1_WALLET)
    .sort("timeStamp", descending=True)
    .unique(subset=["__chain", "hash"], keep="first")
    .with_columns((pl.col("gasUsed") * pl.col("gasPrice") / 1e18).alias("gas_cost"))
    .group_by("__chain").agg(pl.col("gas_cost").sum().round(6).alias("exp_gas"))
    .sort("__chain")
)

got_wallet = doc_s1_b["wallets"][0]
got_gas = pl.DataFrame([{"__chain": c["chain"], "got_gas": round(c["total_gas_burned"],6)}
                         for c in got_wallet["chains"]]).sort("__chain")

def chk(label, exp, got, tol=None):
    ok = (abs(exp-got)<tol) if tol else (exp==got)
    print(f"  {'✓' if ok else '✗'}  {label:<38} expected={exp}  got={got}")

print("Sanity check:")
chk("total_transactions_count", exp_tx,   doc_s1_b["total_transactions_count"])
chk("active_days (user)",       exp_days, doc_s1_b["active_days"])
chk("_first_tx_date",           exp_first, got_wallet["_first_tx_date"])
print()
print("Per-chain gas_burned:")
exp_gas_by_chain.join(got_gas, on="__chain", how="outer")

Sanity check:
  ✓  total_transactions_count               expected=1839  got=1839
  ✗  active_days (user)                     expected=70  got=126
  ✓  _first_tx_date                         expected=2021-06-07  got=2021-06-07

Per-chain gas_burned:

/tmp/ipykernel_231310/1556939142.py:34: DeprecationWarning: use of `how='outer'` should be replaced with `how='full'`.
(Deprecated in version 0.20.29)
  exp_gas_by_chain.join(got_gas, on="__chain", how="outer")

shape: (2, 4)
┌──────────┬──────────┬───────────────┬──────────┐
│ __chain  ┆ exp_gas  ┆ __chain_right ┆ got_gas  │
│ ---      ┆ ---      ┆ ---           ┆ ---      │
│ str      ┆ f64      ┆ str           ┆ f64      │
╞══════════╪══════════╪═══════════════╪══════════╡
│ ethereum ┆ 0.083914 ┆ ethereum      ┆ 0.083914 │
│ polygon  ┆ 3.643132 ┆ polygon       ┆ 3.643133 │
└──────────┴──────────┴───────────────┴──────────┘

---
## Scenario 2 · Single user, multiple wallets

- **User** : `69d693b1ba9f20d582dae331` (3 wallets)
- Each wallet: Batch A → `first_time_flow`, then Batch B → `daily_flow`
- After each `first_time_flow` call the document gains one more wallet entry.
- The `daily_flow` calls update each wallet while preserving the others.

In [13]:
S2_USER    = "69d693b1ba9f20d582dae331"
S2_WALLETS = USERS[S2_USER]

print("── Cleanup ──")
cleanup(S2_USER)

── Cleanup ──
  MongoDB : removed 0 doc  user=69d693b1ba9f20d582dae331
  Staging : removed tmp_test/69d693b1ba9f20d582dae331

### Batch A → first_time_flow for each wallet

In [17]:
for wallet in S2_WALLETS:
    print(f"\n{'='*70}")
    print(f"  first_time_flow: {wallet}")
    print(f"{'='*70}")
    stage(S2_USER, wallet, BATCH_A)
    print()
    first_time_flow(S2_USER, wallet, TEST_ROOT)

======================================================================
  first_time_flow: 0x02d650eea6458794b57492aca061fdbd26d97767
======================================================================
  staged  wallet=0x02d650eea645…  batches=[1, 2, 3]

04:38:24  INFO      PREVIOUS RUN  no existing document found — this is a first-time run
04:38:24  INFO      FIRST-TIME BATCH  wallet=0x02d650eea6458794b57492aca061fdbd26d97767  ──────────────────────────────────────
04:38:24  INFO          wallet-level active_days in this batch: 67
04:38:24  INFO            chain=polygon      first_tx=2021-06-07  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:38:24  INFO            chain=ethereum     first_tx=2024-02-22  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:38:24  INFO      ────────────────────────────────────────────────────────────────────────
04:38:24  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:38:24  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:38:24  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:38:24  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:38:24  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:38:24  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  first_time_flow: 0x353479020cd3d3327af1589ad73d067c75f2dece
======================================================================
  staged  wallet=0x353479020cd3…  batches=[1, 2, 3]

04:38:24  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:38:24  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:38:24  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:38:24  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:38:24  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:38:24  INFO      ────────────────────────────────────────────────────────────────────────
04:38:24  INFO      FIRST-TIME BATCH  wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  ──────────────────────────────────────
04:38:24  INFO          wallet-level active_days in this batch: 57
04:38:24  INFO            chain=arbitrum     first_tx=2024-07-03  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:38:24  INFO            chain=polygon      first_tx=2021-04-24  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:38:24  INFO            chain=ethereum     first_tx=2021-03-19  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:38:24  INFO      ────────────────────────────────────────────────────────────────────────
04:38:25  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:38:25  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=124   tx_count=1263
04:38:25  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:38:25  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:38:25  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:38:25  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:38:25  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:38:25  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:38:25  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:38:25  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  first_time_flow: 0x9f56506dea67eb73f1f2887fbcceca223ee71a42
======================================================================
  staged  wallet=0x9f56506dea67…  batches=[1, 2, 3]

04:38:25  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:38:25  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=124   tx_count=1263
04:38:25  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:38:25  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:38:25  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:38:25  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:38:25  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:38:25  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:38:25  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:38:25  INFO      ────────────────────────────────────────────────────────────────────────
04:38:25  INFO      FIRST-TIME BATCH  wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  ──────────────────────────────────────
04:38:25  INFO          wallet-level active_days in this batch: 279
04:38:25  INFO            chain=arbitrum     first_tx=2022-10-20  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:38:25  INFO            chain=ethereum     first_tx=2021-09-16  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:38:25  INFO            chain=polygon      first_tx=2021-05-02  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:38:25  INFO      ────────────────────────────────────────────────────────────────────────
04:38:26  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:38:26  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=403   tx_count=2019
04:38:26  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:38:26  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:38:26  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:38:26  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:38:26  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:38:26  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:38:26  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:38:26  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:38:26  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:38:26  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:38:26  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:38:26  INFO      ────────────────────────────────────────────────────────────────────────

In [18]:
doc_s2_a = fetch_user_doc(S2_USER)
assert doc_s2_a, "Document not found!"
assert len(doc_s2_a["wallets"]) == len(S2_WALLETS), \
    f"Expected {len(S2_WALLETS)} wallets, got {len(doc_s2_a['wallets'])}"
show_doc(doc_s2_a, "After Batch A — all 3 wallets")

────────────────────────────────────────────────────────────
  After Batch A — all 3 wallets
────────────────────────────────────────────────────────────
{
  "user_id": "69d693b1ba9f20d582dae331",
  "wallet_age_days": 1889,
  "active_days": 403,
  "total_transactions_count": 2019,
  "_first_tx_date": "2021-03-19",
  "last_updated_date": "2026-05-21T04:38:25.716597+00:00"
}

  wallet : 0x9f56506dea67eb73f1f2887fbcceca223ee71a42
           wallet_age=1845d  active_days=279  tx_count=756  first_tx=2021-05-02
    chain=arbitrum     wallet_age=1309d  active_days=7    tx_count=15    gas=0.000434  first_tx=2022-10-20
    chain=ethereum     wallet_age=1708d  active_days=169  tx_count=384   gas=1.546724  first_tx=2021-09-16
    chain=polygon      wallet_age=1845d  active_days=110  tx_count=357   gas=2.435880  first_tx=2021-05-02

  wallet : 0x353479020cd3d3327af1589ad73d067c75f2dece
           wallet_age=1889d  active_days=57  tx_count=158  first_tx=2021-03-19
    chain=arbitrum     wallet_age=687d  active_days=2    tx_count=3     gas=0.000003  first_tx=2024-07-03
    chain=polygon      wallet_age=1853d  active_days=30   tx_count=114   gas=0.866874  first_tx=2021-04-24
    chain=ethereum     wallet_age=1889d  active_days=26   tx_count=41    gas=0.195276  first_tx=2021-03-19

  wallet : 0x02d650eea6458794b57492aca061fdbd26d97767
           wallet_age=1809d  active_days=67  tx_count=1105  first_tx=2021-06-07
    chain=polygon      wallet_age=1809d  active_days=64   tx_count=1100  gas=2.328805  first_tx=2021-06-07
    chain=ethereum     wallet_age=819d  active_days=3    tx_count=5     gas=0.081355  first_tx=2024-02-22

### Batch B → daily_flow for each wallet

In [19]:
for wallet in S2_WALLETS:
    print(f"\n{'='*70}")
    print(f"  daily_flow: {wallet}")
    print(f"{'='*70}")
    stage(S2_USER, wallet, BATCH_B)
    print()
    daily_flow(S2_USER, wallet, TEST_ROOT)

======================================================================
  daily_flow: 0x02d650eea6458794b57492aca061fdbd26d97767
======================================================================
  staged  wallet=0x02d650eea645…  batches=[4, 5]

04:40:42  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:40:42  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=403   tx_count=2019
04:40:42  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:40:42  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:40:42  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:40:42  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:40:42  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:40:42  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:40:42  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:40:42  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:40:42  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:40:42  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:40:42  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:40:42  INFO      ────────────────────────────────────────────────────────────────────────
04:40:42  INFO      DELTA BATCH  wallet=0x02d650eea6458794b57492aca061fdbd26d97767  ──────────────────────────────────────
04:40:42  INFO          wallet-level active_days in this batch: 59
04:40:42  INFO            chain=polygon      first_tx=2021-06-07  active_days=57    tx_count=732    gas_burned=1.314328 ETH
04:40:42  INFO            chain=ethereum     first_tx=2024-02-23  active_days=2     tx_count=2      gas_burned=0.002559 ETH
04:40:42  INFO      ────────────────────────────────────────────────────────────────────────
04:40:42  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:40:42  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=462   tx_count=2753
04:40:42  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:40:42  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:40:42  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:40:42  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:40:42  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:40:42  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:40:42  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:40:42  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:40:42  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:40:42  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:40:42  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:40:42  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  daily_flow: 0x353479020cd3d3327af1589ad73d067c75f2dece
======================================================================
  staged  wallet=0x353479020cd3…  batches=[4, 5]

04:40:42  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:40:42  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=462   tx_count=2753
04:40:42  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:40:42  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:40:42  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:40:42  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:40:42  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:40:42  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:40:42  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:40:42  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:40:42  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:40:42  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:40:42  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:40:42  INFO      ────────────────────────────────────────────────────────────────────────
04:40:42  INFO      DELTA BATCH  wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  ──────────────────────────────────────
04:40:42  INFO          wallet-level active_days in this batch: 40
04:40:42  INFO            chain=ethereum     first_tx=2021-03-20  active_days=16    tx_count=26     gas_burned=0.098812 ETH
04:40:42  INFO            chain=polygon      first_tx=2021-04-24  active_days=23    tx_count=74     gas_burned=0.548050 ETH
04:40:42  INFO            chain=arbitrum     first_tx=2024-07-03  active_days=1     tx_count=2      gas_burned=0.000001 ETH
04:40:42  INFO      ────────────────────────────────────────────────────────────────────────
04:40:43  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:40:43  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=502   tx_count=2855
04:40:43  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=97    tx_count=260
04:40:43  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=42    tx_count=67     gas_burned=0.294088 ETH
04:40:43  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=53    tx_count=188    gas_burned=1.414924 ETH
04:40:43  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=3     tx_count=5      gas_burned=0.000004 ETH
04:40:43  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:40:43  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:40:43  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:40:43  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:40:43  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:40:43  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:40:43  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:40:43  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  daily_flow: 0x9f56506dea67eb73f1f2887fbcceca223ee71a42
======================================================================
  staged  wallet=0x9f56506dea67…  batches=[4, 5]

04:40:43  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:40:43  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=502   tx_count=2855
04:40:43  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=97    tx_count=260
04:40:43  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=42    tx_count=67     gas_burned=0.294088 ETH
04:40:43  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=53    tx_count=188    gas_burned=1.414924 ETH
04:40:43  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=3     tx_count=5      gas_burned=0.000004 ETH
04:40:43  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:40:43  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:40:43  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:40:43  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:40:43  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:40:43  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:40:43  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:40:43  INFO      ────────────────────────────────────────────────────────────────────────
04:40:43  INFO      DELTA BATCH  wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  ──────────────────────────────────────
04:40:43  INFO          wallet-level active_days in this batch: 229
04:40:43  INFO            chain=polygon      first_tx=2021-05-02  active_days=91    tx_count=237    gas_burned=1.920314 ETH
04:40:43  INFO            chain=arbitrum     first_tx=2024-07-03  active_days=6     tx_count=8      gas_burned=0.000031 ETH
04:40:43  INFO            chain=ethereum     first_tx=2021-10-04  active_days=134   tx_count=254    gas_burned=0.845751 ETH
04:40:43  INFO      ────────────────────────────────────────────────────────────────────────
04:40:44  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:40:44  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=731   tx_count=3354
04:40:44  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=508   tx_count=1255
04:40:44  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=201   tx_count=594    gas_burned=4.356194 ETH
04:40:44  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=13    tx_count=23     gas_burned=0.000465 ETH
04:40:44  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=303   tx_count=638    gas_burned=2.392475 ETH
04:40:44  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=97    tx_count=260
04:40:44  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=42    tx_count=67     gas_burned=0.294088 ETH
04:40:44  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=53    tx_count=188    gas_burned=1.414924 ETH
04:40:44  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=3     tx_count=5      gas_burned=0.000004 ETH
04:40:44  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:40:44  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:40:44  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:40:44  INFO      ────────────────────────────────────────────────────────────────────────

In [20]:
doc_s2_b = fetch_user_doc(S2_USER)
assert len(doc_s2_b["wallets"]) == len(S2_WALLETS), \
    f"Expected {len(S2_WALLETS)} wallets, got {len(doc_s2_b['wallets'])}"
show_doc(doc_s2_b, "After Batch B — all 3 wallets updated")

────────────────────────────────────────────────────────────
  After Batch B — all 3 wallets updated
────────────────────────────────────────────────────────────
{
  "user_id": "69d693b1ba9f20d582dae331",
  "wallet_age_days": 1889,
  "active_days": 731,
  "total_transactions_count": 3354,
  "_first_tx_date": "2021-03-19",
  "last_updated_date": "2026-05-21T04:40:43.839777+00:00"
}

  wallet : 0x9f56506dea67eb73f1f2887fbcceca223ee71a42
           wallet_age=1845d  active_days=508  tx_count=1255  first_tx=2021-05-02
    chain=polygon      wallet_age=1845d  active_days=201  tx_count=594   gas=4.356194  first_tx=2021-05-02
    chain=arbitrum     wallet_age=1309d  active_days=13   tx_count=23    gas=0.000465  first_tx=2022-10-20
    chain=ethereum     wallet_age=1708d  active_days=303  tx_count=638   gas=2.392475  first_tx=2021-09-16

  wallet : 0x353479020cd3d3327af1589ad73d067c75f2dece
           wallet_age=1889d  active_days=97  tx_count=260  first_tx=2021-03-19
    chain=ethereum     wallet_age=1889d  active_days=42   tx_count=67    gas=0.294088  first_tx=2021-03-19
    chain=polygon      wallet_age=1853d  active_days=53   tx_count=188   gas=1.414924  first_tx=2021-04-24
    chain=arbitrum     wallet_age=687d  active_days=3    tx_count=5     gas=0.000004  first_tx=2024-07-03

  wallet : 0x02d650eea6458794b57492aca061fdbd26d97767
           wallet_age=1809d  active_days=126  tx_count=1839  first_tx=2021-06-07
    chain=polygon      wallet_age=1809d  active_days=121  tx_count=1832  gas=3.643133  first_tx=2021-06-07
    chain=ethereum     wallet_age=819d  active_days=5    tx_count=7     gas=0.083914  first_tx=2024-02-22

In [21]:
# Per-wallet diff: Batch A → Final
wallets_a = {w["wallet_address"]: w for w in doc_s2_a["wallets"]}
wallets_b = {w["wallet_address"]: w for w in doc_s2_b["wallets"]}

rows = []
for addr in S2_WALLETS:
    wa, wb = wallets_a.get(addr, {}), wallets_b.get(addr, {})
    rows.append({
        "wallet":             addr[:14] + "…",
        "active_days_A":      wa.get("active_days"),
        "active_days_final":  wb.get("active_days"),
        "tx_count_A":         wa.get("total_transactions_count"),
        "tx_count_final":     wb.get("total_transactions_count"),
    })
print("Per-wallet diff (Batch A → Final):")
pl.DataFrame(rows)

Per-wallet diff (Batch A → Final):

shape: (3, 5)
┌─────────────────┬───────────────┬───────────────────┬────────────┬────────────────┐
│ wallet          ┆ active_days_A ┆ active_days_final ┆ tx_count_A ┆ tx_count_final │
│ ---             ┆ ---           ┆ ---               ┆ ---        ┆ ---            │
│ str             ┆ i64           ┆ i64               ┆ i64        ┆ i64            │
╞═════════════════╪═══════════════╪═══════════════════╪════════════╪════════════════╡
│ 0x02d650eea645… ┆ 67            ┆ 126               ┆ 1105       ┆ 1839           │
│ 0x353479020cd3… ┆ 57            ┆ 97                ┆ 158        ┆ 260            │
│ 0x9f56506dea67… ┆ 279           ┆ 508               ┆ 756        ┆ 1255           │
└─────────────────┴───────────────┴───────────────────┴────────────┴────────────────┘

---
## Scenario 3 · Multiple users, multiple wallets

- **User 1** : `69d693b1ba9f20d582dae331` — 3 wallets
- **User 2** : `69e29d7ebb75c92bdac43fe1` — 2 wallets
- All wallets across both users: Batch A → `first_time_flow`, then Batch B → `daily_flow`

In [22]:
print("── Cleanup ──")
for user_id in USERS:
    cleanup(user_id)

── Cleanup ──
  MongoDB : removed 0 doc  user=69d693b1ba9f20d582dae331
  Staging : removed tmp_test/69d693b1ba9f20d582dae331
  MongoDB : removed 1 doc  user=69e29d7ebb75c92bdac43fe1

### Batch A → first_time_flow for all users and wallets

In [23]:
for user_id, wallets in USERS.items():
    for wallet in wallets:
        print(f"\n{'='*70}")
        print(f"  first_time_flow  user={user_id}  wallet={wallet}")
        print(f"{'='*70}")
        stage(user_id, wallet, BATCH_A)
        print()
        first_time_flow(user_id, wallet, TEST_ROOT)

======================================================================
  first_time_flow  user=69d693b1ba9f20d582dae331  wallet=0x02d650eea6458794b57492aca061fdbd26d97767
======================================================================
  staged  wallet=0x02d650eea645…  batches=[1, 2, 3]

04:41:30  INFO      PREVIOUS RUN  no existing document found — this is a first-time run
04:41:30  INFO      FIRST-TIME BATCH  wallet=0x02d650eea6458794b57492aca061fdbd26d97767  ──────────────────────────────────────
04:41:30  INFO          wallet-level active_days in this batch: 67
04:41:30  INFO            chain=polygon      first_tx=2021-06-07  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:41:30  INFO            chain=ethereum     first_tx=2024-02-22  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:41:30  INFO      ────────────────────────────────────────────────────────────────────────
04:41:30  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:41:30  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:41:30  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:41:30  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:41:30  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:41:30  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  first_time_flow  user=69d693b1ba9f20d582dae331  wallet=0x353479020cd3d3327af1589ad73d067c75f2dece
======================================================================
  staged  wallet=0x353479020cd3…  batches=[1, 2, 3]

04:41:31  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:41:31  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:41:31  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:41:31  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:41:31  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:41:31  INFO      ────────────────────────────────────────────────────────────────────────
04:41:31  INFO      FIRST-TIME BATCH  wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  ──────────────────────────────────────
04:41:31  INFO          wallet-level active_days in this batch: 57
04:41:31  INFO            chain=ethereum     first_tx=2021-03-19  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:41:31  INFO            chain=arbitrum     first_tx=2024-07-03  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:41:31  INFO            chain=polygon      first_tx=2021-04-24  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:41:31  INFO      ────────────────────────────────────────────────────────────────────────
04:41:31  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:41:31  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=124   tx_count=1263
04:41:31  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:41:31  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:41:31  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:41:31  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:41:31  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:41:31  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:41:31  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:41:31  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  first_time_flow  user=69d693b1ba9f20d582dae331  wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42
======================================================================
  staged  wallet=0x9f56506dea67…  batches=[1, 2, 3]

04:41:31  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:41:31  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=124   tx_count=1263
04:41:31  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:41:31  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:41:31  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:41:31  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:41:31  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:41:31  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:41:31  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:41:31  INFO      ────────────────────────────────────────────────────────────────────────
04:41:31  INFO      FIRST-TIME BATCH  wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  ──────────────────────────────────────
04:41:31  INFO          wallet-level active_days in this batch: 279
04:41:31  INFO            chain=polygon      first_tx=2021-05-02  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:41:31  INFO            chain=ethereum     first_tx=2021-09-16  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:41:31  INFO            chain=arbitrum     first_tx=2022-10-20  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:41:31  INFO      ────────────────────────────────────────────────────────────────────────
04:41:32  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:41:32  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=403   tx_count=2019
04:41:32  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:41:32  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:41:32  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:41:32  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:41:32  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:41:32  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:41:32  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:41:32  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:41:32  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:41:32  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:41:32  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:41:32  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  first_time_flow  user=69e29d7ebb75c92bdac43fe1  wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9
======================================================================
  staged  wallet=0x0d53ab1ede05…  batches=[1, 2, 3]

04:41:32  INFO      PREVIOUS RUN  no existing document found — this is a first-time run
04:41:32  INFO      FIRST-TIME BATCH  wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9  ──────────────────────────────────────
04:41:32  INFO          wallet-level active_days in this batch: 173
04:41:32  INFO            chain=ethereum     first_tx=2021-06-12  active_days=163   tx_count=300    gas_burned=0.788219 ETH
04:41:32  INFO            chain=polygon      first_tx=2021-07-18  active_days=11    tx_count=15     gas_burned=0.079800 ETH
04:41:32  INFO      ────────────────────────────────────────────────────────────────────────
04:41:33  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:41:33  INFO        user=69e29d7ebb75c92bdac43fe1  first_tx=2021-06-12  wallet_age=1804d  active_days=173   tx_count=315
04:41:33  INFO          wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9  first_tx=2021-06-12  wallet_age=1804d  active_days=173   tx_count=315
04:41:33  INFO            chain=ethereum     first_tx=2021-06-12  wallet_age=1804d  active_days=163   tx_count=300    gas_burned=0.788219 ETH
04:41:33  INFO            chain=polygon      first_tx=2021-07-18  wallet_age=1768d  active_days=11    tx_count=15     gas_burned=0.079800 ETH
04:41:33  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  first_time_flow  user=69e29d7ebb75c92bdac43fe1  wallet=0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691
======================================================================
  staged  wallet=0x73d2a51ba95f…  batches=[1, 2, 3]

04:41:33  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:41:33  INFO        user=69e29d7ebb75c92bdac43fe1  first_tx=2021-06-12  wallet_age=1804d  active_days=173   tx_count=315
04:41:33  INFO          wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9  first_tx=2021-06-12  wallet_age=1804d  active_days=173   tx_count=315
04:41:33  INFO            chain=ethereum     first_tx=2021-06-12  wallet_age=1804d  active_days=163   tx_count=300    gas_burned=0.788219 ETH
04:41:33  INFO            chain=polygon      first_tx=2021-07-18  wallet_age=1768d  active_days=11    tx_count=15     gas_burned=0.079800 ETH
04:41:33  INFO      ────────────────────────────────────────────────────────────────────────
04:41:33  INFO      FIRST-TIME BATCH  wallet=0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691  ──────────────────────────────────────
04:41:33  INFO          wallet-level active_days in this batch: 587
04:41:33  INFO            chain=arbitrum     first_tx=2024-03-25  active_days=78    tx_count=128    gas_burned=0.000138 ETH
04:41:33  INFO            chain=polygon      first_tx=2022-10-23  active_days=135   tx_count=291    gas_burned=1.687869 ETH
04:41:33  INFO            chain=ethereum     first_tx=2022-07-01  active_days=419   tx_count=934    gas_burned=1.012251 ETH
04:41:33  INFO      ────────────────────────────────────────────────────────────────────────
04:41:33  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:41:33  INFO        user=69e29d7ebb75c92bdac43fe1  first_tx=2021-06-12  wallet_age=1804d  active_days=760   tx_count=1668
04:41:33  INFO          wallet=0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691  first_tx=2022-07-01  wallet_age=1420d  active_days=587   tx_count=1353
04:41:33  INFO            chain=arbitrum     first_tx=2024-03-25  wallet_age=787d  active_days=78    tx_count=128    gas_burned=0.000138 ETH
04:41:33  INFO            chain=polygon      first_tx=2022-10-23  wallet_age=1306d  active_days=135   tx_count=291    gas_burned=1.687869 ETH
04:41:33  INFO            chain=ethereum     first_tx=2022-07-01  wallet_age=1420d  active_days=419   tx_count=934    gas_burned=1.012251 ETH
04:41:33  INFO          wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9  first_tx=2021-06-12  wallet_age=1804d  active_days=173   tx_count=315
04:41:33  INFO            chain=ethereum     first_tx=2021-06-12  wallet_age=1804d  active_days=163   tx_count=300    gas_burned=0.788219 ETH
04:41:33  INFO            chain=polygon      first_tx=2021-07-18  wallet_age=1768d  active_days=11    tx_count=15     gas_burned=0.079800 ETH
04:41:33  INFO      ────────────────────────────────────────────────────────────────────────

In [24]:
print("── Verify: both user documents after Batch A ──")
for user_id, wallets in USERS.items():
    doc = fetch_user_doc(user_id)
    assert doc, f"Document not found for {user_id}"
    assert len(doc["wallets"]) == len(wallets), \
        f"user={user_id}: expected {len(wallets)} wallets, got {len(doc['wallets'])}"
    show_doc(doc, f"user={user_id}  ({len(wallets)} wallets)")

── Verify: both user documents after Batch A ──

────────────────────────────────────────────────────────────
  user=69d693b1ba9f20d582dae331  (3 wallets)
────────────────────────────────────────────────────────────
{
  "user_id": "69d693b1ba9f20d582dae331",
  "wallet_age_days": 1889,
  "active_days": 403,
  "total_transactions_count": 2019,
  "_first_tx_date": "2021-03-19",
  "last_updated_date": "2026-05-21T04:41:31.953154+00:00"
}

  wallet : 0x9f56506dea67eb73f1f2887fbcceca223ee71a42
           wallet_age=1845d  active_days=279  tx_count=756  first_tx=2021-05-02
    chain=polygon      wallet_age=1845d  active_days=110  tx_count=357   gas=2.435880  first_tx=2021-05-02
    chain=ethereum     wallet_age=1708d  active_days=169  tx_count=384   gas=1.546724  first_tx=2021-09-16
    chain=arbitrum     wallet_age=1309d  active_days=7    tx_count=15    gas=0.000434  first_tx=2022-10-20

  wallet : 0x353479020cd3d3327af1589ad73d067c75f2dece
           wallet_age=1889d  active_days=57  tx_count=158  first_tx=2021-03-19
    chain=ethereum     wallet_age=1889d  active_days=26   tx_count=41    gas=0.195276  first_tx=2021-03-19
    chain=arbitrum     wallet_age=687d  active_days=2    tx_count=3     gas=0.000003  first_tx=2024-07-03
    chain=polygon      wallet_age=1853d  active_days=30   tx_count=114   gas=0.866874  first_tx=2021-04-24

  wallet : 0x02d650eea6458794b57492aca061fdbd26d97767
           wallet_age=1809d  active_days=67  tx_count=1105  first_tx=2021-06-07
    chain=polygon      wallet_age=1809d  active_days=64   tx_count=1100  gas=2.328805  first_tx=2021-06-07
    chain=ethereum     wallet_age=819d  active_days=3    tx_count=5     gas=0.081355  first_tx=2024-02-22

────────────────────────────────────────────────────────────
  user=69e29d7ebb75c92bdac43fe1  (2 wallets)
────────────────────────────────────────────────────────────
{
  "user_id": "69e29d7ebb75c92bdac43fe1",
  "wallet_age_days": 1804,
  "active_days": 760,
  "total_transactions_count": 1668,
  "_first_tx_date": "2021-06-12",
  "last_updated_date": "2026-05-21T04:41:33.446616+00:00"
}

  wallet : 0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691
           wallet_age=1420d  active_days=587  tx_count=1353  first_tx=2022-07-01
    chain=arbitrum     wallet_age=787d  active_days=78   tx_count=128   gas=0.000138  first_tx=2024-03-25
    chain=polygon      wallet_age=1306d  active_days=135  tx_count=291   gas=1.687869  first_tx=2022-10-23
    chain=ethereum     wallet_age=1420d  active_days=419  tx_count=934   gas=1.012251  first_tx=2022-07-01

  wallet : 0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9
           wallet_age=1804d  active_days=173  tx_count=315  first_tx=2021-06-12
    chain=ethereum     wallet_age=1804d  active_days=163  tx_count=300   gas=0.788219  first_tx=2021-06-12
    chain=polygon      wallet_age=1768d  active_days=11   tx_count=15    gas=0.079800  first_tx=2021-07-18

### Batch B → daily_flow for all users and wallets

In [25]:
for user_id, wallets in USERS.items():
    for wallet in wallets:
        print(f"\n{'='*70}")
        print(f"  daily_flow  user={user_id}  wallet={wallet}")
        print(f"{'='*70}")
        stage(user_id, wallet, BATCH_B)
        print()
        daily_flow(user_id, wallet, TEST_ROOT)

======================================================================
  daily_flow  user=69d693b1ba9f20d582dae331  wallet=0x02d650eea6458794b57492aca061fdbd26d97767
======================================================================
  staged  wallet=0x02d650eea645…  batches=[4, 5]

04:41:45  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:41:45  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=403   tx_count=2019
04:41:45  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:41:45  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:41:45  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:41:45  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:41:45  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:41:45  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:41:45  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:41:45  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:41:45  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=67    tx_count=1105
04:41:45  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=64    tx_count=1100   gas_burned=2.328805 ETH
04:41:45  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=3     tx_count=5      gas_burned=0.081355 ETH
04:41:45  INFO      ────────────────────────────────────────────────────────────────────────
04:41:45  INFO      DELTA BATCH  wallet=0x02d650eea6458794b57492aca061fdbd26d97767  ──────────────────────────────────────
04:41:45  INFO          wallet-level active_days in this batch: 59
04:41:45  INFO            chain=ethereum     first_tx=2024-02-23  active_days=2     tx_count=2      gas_burned=0.002559 ETH
04:41:45  INFO            chain=polygon      first_tx=2021-06-07  active_days=57    tx_count=732    gas_burned=1.314328 ETH
04:41:45  INFO      ────────────────────────────────────────────────────────────────────────
04:41:45  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:41:45  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=462   tx_count=2753
04:41:45  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:41:45  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:41:45  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:41:45  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:41:45  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:41:45  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:41:45  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:41:45  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:41:45  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:41:45  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:41:45  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:41:45  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  daily_flow  user=69d693b1ba9f20d582dae331  wallet=0x353479020cd3d3327af1589ad73d067c75f2dece
======================================================================
  staged  wallet=0x353479020cd3…  batches=[4, 5]

04:41:46  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:41:46  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=462   tx_count=2753
04:41:46  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:41:46  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:41:46  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:41:46  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:41:46  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:41:46  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:41:46  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:41:46  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=57    tx_count=158
04:41:46  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=26    tx_count=41     gas_burned=0.195276 ETH
04:41:46  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=2     tx_count=3      gas_burned=0.000003 ETH
04:41:46  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=30    tx_count=114    gas_burned=0.866874 ETH
04:41:46  INFO      ────────────────────────────────────────────────────────────────────────
04:41:46  INFO      DELTA BATCH  wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  ──────────────────────────────────────
04:41:46  INFO          wallet-level active_days in this batch: 40
04:41:46  INFO            chain=ethereum     first_tx=2021-03-20  active_days=16    tx_count=26     gas_burned=0.098812 ETH
04:41:46  INFO            chain=polygon      first_tx=2021-04-24  active_days=23    tx_count=74     gas_burned=0.548050 ETH
04:41:46  INFO            chain=arbitrum     first_tx=2024-07-03  active_days=1     tx_count=2      gas_burned=0.000001 ETH
04:41:46  INFO      ────────────────────────────────────────────────────────────────────────
04:41:46  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:41:46  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=502   tx_count=2855
04:41:46  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=97    tx_count=260
04:41:46  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=42    tx_count=67     gas_burned=0.294088 ETH
04:41:46  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=53    tx_count=188    gas_burned=1.414924 ETH
04:41:46  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=3     tx_count=5      gas_burned=0.000004 ETH
04:41:46  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:41:46  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:41:46  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:41:46  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:41:46  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:41:46  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:41:46  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:41:46  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  daily_flow  user=69d693b1ba9f20d582dae331  wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42
======================================================================
  staged  wallet=0x9f56506dea67…  batches=[4, 5]

04:41:46  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:41:46  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=502   tx_count=2855
04:41:46  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=97    tx_count=260
04:41:46  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=42    tx_count=67     gas_burned=0.294088 ETH
04:41:46  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=53    tx_count=188    gas_burned=1.414924 ETH
04:41:46  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=3     tx_count=5      gas_burned=0.000004 ETH
04:41:46  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:41:46  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:41:46  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:41:46  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=279   tx_count=756
04:41:46  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=110   tx_count=357    gas_burned=2.435880 ETH
04:41:46  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=169   tx_count=384    gas_burned=1.546724 ETH
04:41:46  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=7     tx_count=15     gas_burned=0.000434 ETH
04:41:46  INFO      ────────────────────────────────────────────────────────────────────────
04:41:46  INFO      DELTA BATCH  wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  ──────────────────────────────────────
04:41:46  INFO          wallet-level active_days in this batch: 229
04:41:46  INFO            chain=polygon      first_tx=2021-05-02  active_days=91    tx_count=237    gas_burned=1.920314 ETH
04:41:46  INFO            chain=ethereum     first_tx=2021-10-04  active_days=134   tx_count=254    gas_burned=0.845751 ETH
04:41:46  INFO            chain=arbitrum     first_tx=2024-07-03  active_days=6     tx_count=8      gas_burned=0.000031 ETH
04:41:46  INFO      ────────────────────────────────────────────────────────────────────────
04:41:47  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:41:47  INFO        user=69d693b1ba9f20d582dae331  first_tx=2021-03-19  wallet_age=1889d  active_days=731   tx_count=3354
04:41:47  INFO          wallet=0x9f56506dea67eb73f1f2887fbcceca223ee71a42  first_tx=2021-05-02  wallet_age=1845d  active_days=508   tx_count=1255
04:41:47  INFO            chain=polygon      first_tx=2021-05-02  wallet_age=1845d  active_days=201   tx_count=594    gas_burned=4.356194 ETH
04:41:47  INFO            chain=ethereum     first_tx=2021-09-16  wallet_age=1708d  active_days=303   tx_count=638    gas_burned=2.392475 ETH
04:41:47  INFO            chain=arbitrum     first_tx=2022-10-20  wallet_age=1309d  active_days=13    tx_count=23     gas_burned=0.000465 ETH
04:41:47  INFO          wallet=0x353479020cd3d3327af1589ad73d067c75f2dece  first_tx=2021-03-19  wallet_age=1889d  active_days=97    tx_count=260
04:41:47  INFO            chain=ethereum     first_tx=2021-03-19  wallet_age=1889d  active_days=42    tx_count=67     gas_burned=0.294088 ETH
04:41:47  INFO            chain=polygon      first_tx=2021-04-24  wallet_age=1853d  active_days=53    tx_count=188    gas_burned=1.414924 ETH
04:41:47  INFO            chain=arbitrum     first_tx=2024-07-03  wallet_age=687d  active_days=3     tx_count=5      gas_burned=0.000004 ETH
04:41:47  INFO          wallet=0x02d650eea6458794b57492aca061fdbd26d97767  first_tx=2021-06-07  wallet_age=1809d  active_days=126   tx_count=1839
04:41:47  INFO            chain=ethereum     first_tx=2024-02-22  wallet_age=819d  active_days=5     tx_count=7      gas_burned=0.083914 ETH
04:41:47  INFO            chain=polygon      first_tx=2021-06-07  wallet_age=1809d  active_days=121   tx_count=1832   gas_burned=3.643133 ETH
04:41:47  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  daily_flow  user=69e29d7ebb75c92bdac43fe1  wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9
======================================================================
  staged  wallet=0x0d53ab1ede05…  batches=[4, 5]

04:41:47  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:41:47  INFO        user=69e29d7ebb75c92bdac43fe1  first_tx=2021-06-12  wallet_age=1804d  active_days=760   tx_count=1668
04:41:47  INFO          wallet=0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691  first_tx=2022-07-01  wallet_age=1420d  active_days=587   tx_count=1353
04:41:47  INFO            chain=arbitrum     first_tx=2024-03-25  wallet_age=787d  active_days=78    tx_count=128    gas_burned=0.000138 ETH
04:41:47  INFO            chain=polygon      first_tx=2022-10-23  wallet_age=1306d  active_days=135   tx_count=291    gas_burned=1.687869 ETH
04:41:47  INFO            chain=ethereum     first_tx=2022-07-01  wallet_age=1420d  active_days=419   tx_count=934    gas_burned=1.012251 ETH
04:41:47  INFO          wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9  first_tx=2021-06-12  wallet_age=1804d  active_days=173   tx_count=315
04:41:47  INFO            chain=ethereum     first_tx=2021-06-12  wallet_age=1804d  active_days=163   tx_count=300    gas_burned=0.788219 ETH
04:41:47  INFO            chain=polygon      first_tx=2021-07-18  wallet_age=1768d  active_days=11    tx_count=15     gas_burned=0.079800 ETH
04:41:47  INFO      ────────────────────────────────────────────────────────────────────────
04:41:47  INFO      DELTA BATCH  wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9  ──────────────────────────────────────
04:41:47  INFO          wallet-level active_days in this batch: 127
04:41:47  INFO            chain=ethereum     first_tx=2021-06-12  active_days=120   tx_count=198    gas_burned=0.591177 ETH
04:41:47  INFO            chain=polygon      first_tx=2022-02-03  active_days=8     tx_count=10     gas_burned=0.248308 ETH
04:41:47  INFO      ────────────────────────────────────────────────────────────────────────
04:41:47  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:41:47  INFO        user=69e29d7ebb75c92bdac43fe1  first_tx=2021-06-12  wallet_age=1804d  active_days=887   tx_count=1876
04:41:47  INFO          wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9  first_tx=2021-06-12  wallet_age=1804d  active_days=300   tx_count=523
04:41:47  INFO            chain=ethereum     first_tx=2021-06-12  wallet_age=1804d  active_days=283   tx_count=498    gas_burned=1.379396 ETH
04:41:47  INFO            chain=polygon      first_tx=2021-07-18  wallet_age=1768d  active_days=19    tx_count=25     gas_burned=0.328108 ETH
04:41:47  INFO          wallet=0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691  first_tx=2022-07-01  wallet_age=1420d  active_days=587   tx_count=1353
04:41:47  INFO            chain=arbitrum     first_tx=2024-03-25  wallet_age=787d  active_days=78    tx_count=128    gas_burned=0.000138 ETH
04:41:47  INFO            chain=polygon      first_tx=2022-10-23  wallet_age=1306d  active_days=135   tx_count=291    gas_burned=1.687869 ETH
04:41:47  INFO            chain=ethereum     first_tx=2022-07-01  wallet_age=1420d  active_days=419   tx_count=934    gas_burned=1.012251 ETH
04:41:47  INFO      ────────────────────────────────────────────────────────────────────────

======================================================================
  daily_flow  user=69e29d7ebb75c92bdac43fe1  wallet=0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691
======================================================================
  staged  wallet=0x73d2a51ba95f…  batches=[4, 5]

04:41:48  INFO      PREVIOUS RUN  ─────────────────────────────────────────────────────────
04:41:48  INFO        user=69e29d7ebb75c92bdac43fe1  first_tx=2021-06-12  wallet_age=1804d  active_days=887   tx_count=1876
04:41:48  INFO          wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9  first_tx=2021-06-12  wallet_age=1804d  active_days=300   tx_count=523
04:41:48  INFO            chain=ethereum     first_tx=2021-06-12  wallet_age=1804d  active_days=283   tx_count=498    gas_burned=1.379396 ETH
04:41:48  INFO            chain=polygon      first_tx=2021-07-18  wallet_age=1768d  active_days=19    tx_count=25     gas_burned=0.328108 ETH
04:41:48  INFO          wallet=0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691  first_tx=2022-07-01  wallet_age=1420d  active_days=587   tx_count=1353
04:41:48  INFO            chain=arbitrum     first_tx=2024-03-25  wallet_age=787d  active_days=78    tx_count=128    gas_burned=0.000138 ETH
04:41:48  INFO            chain=polygon      first_tx=2022-10-23  wallet_age=1306d  active_days=135   tx_count=291    gas_burned=1.687869 ETH
04:41:48  INFO            chain=ethereum     first_tx=2022-07-01  wallet_age=1420d  active_days=419   tx_count=934    gas_burned=1.012251 ETH
04:41:48  INFO      ────────────────────────────────────────────────────────────────────────
04:41:48  INFO      DELTA BATCH  wallet=0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691  ──────────────────────────────────────
04:41:48  INFO          wallet-level active_days in this batch: 470
04:41:48  INFO            chain=ethereum     first_tx=2022-06-29  active_days=336   tx_count=622    gas_burned=0.668623 ETH
04:41:48  INFO            chain=polygon      first_tx=2022-12-30  active_days=110   tx_count=192    gas_burned=0.972665 ETH
04:41:48  INFO            chain=arbitrum     first_tx=2024-03-25  active_days=59    tx_count=84     gas_burned=0.000169 ETH
04:41:48  INFO      ────────────────────────────────────────────────────────────────────────
04:41:48  INFO      FINAL RESULT  ──────────────────────────────────────────────────────────
04:41:48  INFO        user=69e29d7ebb75c92bdac43fe1  first_tx=2021-06-12  wallet_age=1804d  active_days=1357  tx_count=2774
04:41:48  INFO          wallet=0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691  first_tx=2022-06-29  wallet_age=1422d  active_days=1057  tx_count=2251
04:41:48  INFO            chain=ethereum     first_tx=2022-06-29  wallet_age=1422d  active_days=755   tx_count=1556   gas_burned=1.680874 ETH
04:41:48  INFO            chain=polygon      first_tx=2022-10-23  wallet_age=1306d  active_days=245   tx_count=483    gas_burned=2.660534 ETH
04:41:48  INFO            chain=arbitrum     first_tx=2024-03-25  wallet_age=787d  active_days=137   tx_count=212    gas_burned=0.000307 ETH
04:41:48  INFO          wallet=0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9  first_tx=2021-06-12  wallet_age=1804d  active_days=300   tx_count=523
04:41:48  INFO            chain=ethereum     first_tx=2021-06-12  wallet_age=1804d  active_days=283   tx_count=498    gas_burned=1.379396 ETH
04:41:48  INFO            chain=polygon      first_tx=2021-07-18  wallet_age=1768d  active_days=19    tx_count=25     gas_burned=0.328108 ETH
04:41:48  INFO      ────────────────────────────────────────────────────────────────────────

In [26]:
print("── Verify: both user documents after Batch B ──")
for user_id, wallets in USERS.items():
    doc = fetch_user_doc(user_id)
    assert len(doc["wallets"]) == len(wallets), \
        f"user={user_id}: expected {len(wallets)} wallets, got {len(doc['wallets'])}"
    show_doc(doc, f"user={user_id}  ({len(wallets)} wallets — final)")

── Verify: both user documents after Batch B ──

────────────────────────────────────────────────────────────
  user=69d693b1ba9f20d582dae331  (3 wallets — final)
────────────────────────────────────────────────────────────
{
  "user_id": "69d693b1ba9f20d582dae331",
  "wallet_age_days": 1889,
  "active_days": 731,
  "total_transactions_count": 3354,
  "_first_tx_date": "2021-03-19",
  "last_updated_date": "2026-05-21T04:41:46.824196+00:00"
}

  wallet : 0x9f56506dea67eb73f1f2887fbcceca223ee71a42
           wallet_age=1845d  active_days=508  tx_count=1255  first_tx=2021-05-02
    chain=polygon      wallet_age=1845d  active_days=201  tx_count=594   gas=4.356194  first_tx=2021-05-02
    chain=ethereum     wallet_age=1708d  active_days=303  tx_count=638   gas=2.392475  first_tx=2021-09-16
    chain=arbitrum     wallet_age=1309d  active_days=13   tx_count=23    gas=0.000465  first_tx=2022-10-20

  wallet : 0x353479020cd3d3327af1589ad73d067c75f2dece
           wallet_age=1889d  active_days=97  tx_count=260  first_tx=2021-03-19
    chain=ethereum     wallet_age=1889d  active_days=42   tx_count=67    gas=0.294088  first_tx=2021-03-19
    chain=polygon      wallet_age=1853d  active_days=53   tx_count=188   gas=1.414924  first_tx=2021-04-24
    chain=arbitrum     wallet_age=687d  active_days=3    tx_count=5     gas=0.000004  first_tx=2024-07-03

  wallet : 0x02d650eea6458794b57492aca061fdbd26d97767
           wallet_age=1809d  active_days=126  tx_count=1839  first_tx=2021-06-07
    chain=ethereum     wallet_age=819d  active_days=5    tx_count=7     gas=0.083914  first_tx=2024-02-22
    chain=polygon      wallet_age=1809d  active_days=121  tx_count=1832  gas=3.643133  first_tx=2021-06-07

────────────────────────────────────────────────────────────
  user=69e29d7ebb75c92bdac43fe1  (2 wallets — final)
────────────────────────────────────────────────────────────
{
  "user_id": "69e29d7ebb75c92bdac43fe1",
  "wallet_age_days": 1804,
  "active_days": 1357,
  "total_transactions_count": 2774,
  "_first_tx_date": "2021-06-12",
  "last_updated_date": "2026-05-21T04:41:48.293348+00:00"
}

  wallet : 0x73d2a51ba95f1e05fb271b3f4140617c2bd9c691
           wallet_age=1422d  active_days=1057  tx_count=2251  first_tx=2022-06-29
    chain=ethereum     wallet_age=1422d  active_days=755  tx_count=1556  gas=1.680874  first_tx=2022-06-29
    chain=polygon      wallet_age=1306d  active_days=245  tx_count=483   gas=2.660534  first_tx=2022-10-23
    chain=arbitrum     wallet_age=787d  active_days=137  tx_count=212   gas=0.000307  first_tx=2024-03-25

  wallet : 0x0d53ab1ede05039f6b91b753ddca767cf9a2fad9
           wallet_age=1804d  active_days=300  tx_count=523  first_tx=2021-06-12
    chain=ethereum     wallet_age=1804d  active_days=283  tx_count=498   gas=1.379396  first_tx=2021-06-12
    chain=polygon      wallet_age=1768d  active_days=19   tx_count=25    gas=0.328108  first_tx=2021-07-18

In [27]:
# Cross-user summary: one row per user
rows = []
for user_id in USERS:
    doc = fetch_user_doc(user_id)
    rows.append({
        "user_id":      user_id,
        "wallets":      len(doc["wallets"]),
        "chains_total": sum(len(w["chains"]) for w in doc["wallets"]),
        "wallet_age_days":         doc["wallet_age_days"],
        "active_days":             doc["active_days"],
        "total_transactions_count":doc["total_transactions_count"],
        "first_tx":                doc["_first_tx_date"],
    })
print("Cross-user summary:")
pl.DataFrame(rows)

Cross-user summary:

shape: (2, 7)
┌───────────────┬─────────┬──────────────┬───────────────┬─────────────┬──────────────┬────────────┐
│ user_id       ┆ wallets ┆ chains_total ┆ wallet_age_da ┆ active_days ┆ total_transa ┆ first_tx   │
│ ---           ┆ ---     ┆ ---          ┆ ys            ┆ ---         ┆ ctions_count ┆ ---        │
│ str           ┆ i64     ┆ i64          ┆ ---           ┆ i64         ┆ ---          ┆ str        │
│               ┆         ┆              ┆ i64           ┆             ┆ i64          ┆            │
╞═══════════════╪═════════╪══════════════╪═══════════════╪═════════════╪══════════════╪════════════╡
│ 69d693b1ba9f2 ┆ 3       ┆ 8            ┆ 1889          ┆ 731         ┆ 3354         ┆ 2021-03-19 │
│ 0d582dae331   ┆         ┆              ┆               ┆             ┆              ┆            │
│ 69e29d7ebb75c ┆ 2       ┆ 5            ┆ 1804          ┆ 1357        ┆ 2774         ┆ 2021-06-12 │
│ 92bdac43fe1   ┆         ┆              ┆               ┆             ┆              ┆            │
└───────────────┴─────────┴──────────────┴───────────────┴─────────────┴──────────────┴────────────┘

---
## Cleanup — remove all test data

In [ ]:
for user_id in USERS:
    cleanup(user_id)
print("Done.")